version: "3.9"

services:
  server:
    build: ./backend
    # image: harshsingh2028/streamx-backend:latest
    container_name: server
    networks:
      - fullstack-net
    env_file:
      - path: ./backend/.env
        required: true
    restart: unless-stopped

  client:
    build: 
      context: ./frontend
      args:
        VITE_SERVER: /api
    # image: harshsingh2028/streamx-frontend:latest

    container_name: client
    networks:
      - fullstack-net
    depends_on:
      - server
    
    restart: unless-stopped
  
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - server
      - client
      - prom-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - fullstack-net
    restart: unless-stopped

  prom-server:
    image: prom/prometheus
    # ports:
    #   - 9090:9090
    volumes:
      - ./backend/prometheus-config.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    depends_on:
      - server
    networks:
    - fullstack-net
    restart: unless-stopped
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    #   - GF_AUTH_ANONYMOUS_ENABLED=false
    #   - GF_SECURITY_ADMIN_PASSWORD=strongpassword
    # ports:
    #   - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - fullstack-net
    
networks:
  fullstack-net:
    driver: bridge

volumes:
  grafana-storage: {}
  prometheus-data: {}