name: Deploy Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install k6
        run: |
          snap install k6

      - name: Run Smoke-Test
        run: |
          k6 run test/smoke.test.js