name: StreamX Frontend Docker CI   
on:
  push:
    branches: [ main ]
    paths: 
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and push
      run: |
        docker build -t harshsingh2028/streamx-frontend:latest ./frontend
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push harshsingh2028/streamx-frontend:latest

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@master
      with:  
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/ubuntu/streamx
          docker stop client || true
          docker rm client || true
          docker pull harshsingh2028/streamx-frontend:latest
          docker compose up -d